export class MvcConst {
  public static MSG_COMMAND_EXECUTE = "MSG_COMMAND_EXECUTE";
  public static MSG_COMMAND_UNDO = "MSG_COMMAND_UNDO";
  public static MSG_COMMAND_REDO = "MSG_COMMAND_REDO";
  public static MSG_COMMAND_EVENT = "MSG_COMMAND_EVENT";

  public static MSG_BO_SELECTION_CHANGED = "MSG_BO_SELECTION_CHANGED";
  public static MSG_LIB_SELECTION_CHANGED = "MSG_LIB_SELECTION_CHANGED";
  public static MSG_SVG_SELECTION_CHANGED = "MSG_SVG_SELECTION_CHANGED";

  public static MSG_VIEW_SELECTION_CHANGED = "MSG_VIEW_SELECTION_CHANGED";

  public static MSG_START_LOADING_MODEL = "MSG_START_LOADING_MODEL";
  public static MSG_END_LOADING_MODEL = "MSG_END_LOADING_MODEL";

  public static MSG_START_LAZY_LOADING = "MSG_START_LAZY_LOADING";
  public static MSG_END_LAZY_LOADING = "MSG_END_LAZY_LOADING";

  public static MSG_START_SVG_DIAGRAM_LOADING = "MSG_START_SVG_DIAGRAM_LOADING";
  public static MSG_END_SVG_DIAGRAM_LOADING = "MSG_END_SVG_DIAGRAM_LOADING";

  public static MSG_START_SELECTING_PROJECT = "MSG_START_SELECTING_PROJECT";
  public static MSG_END_SELECTING_PROJECT = "MSG_END_SELECTING_PROJECT";

  public static MSG_START_LOADING_USER_CONFIG = "MSG_START_LOADING_USER_CONFIG";
  public static MSG_END_LOADING_USER_CONFIG = "MSG_END_LOADING_USER_CONFIG";

  public static MSG_END_LOADING_PROJECT_FOR_COMPARISON = "MSG_END_LOADING_PROJECT_FOR_COMPARISON";
  public static MSG_END_LOADING_PROJECT_COMPARISON_FILE = "MSG_END_LOADING_PROJECT_COMPARISON_FILE";
  public static MSG_COMPARISON_ERROR = "MSG_COMPARISON_ERROR";
  public static MSG_RESET_COMPARISON = "MSG_RESET_COMPARISON";

  public static MSG_START_LOADING_APP_CONFIG = "MSG_START_LOADING_APP_CONFIG";
  public static MSG_END_LOADING_APP_CONFIG = "MSG_END_LOADING_APP_CONFIG";

  public static MSG_MODEL_CHANGED = "MSG_MODEL_CHANGE";
  public static MSG_MODEL_CONFIG_CHANGED = "MSG_MODEL_CONFIG_CHANGED";
  public static MSG_XSD_CHANGED = "MSG_XSD_CHANGED";

  public static MSG_SERVER_CHANGED = "MSG_SERVER_CHANGED";
  public static MSG_USER_CHANGED = "MSG_USER_CHANGED";
  public static MSG_REFRESH_VIEW = "MSG_REFRESH_VIEW";

  public static MSG_OPEN_BO_DOCUMENTATION_REQUEST = "MSG_OPEN_BO_DOCUMENTATION_REQUEST";
  public static MSG_OPEN_URL_DOCUMENTATION_REQUEST = "MSG_OPEN_URL_DOCUMENTATION_REQUEST";

  public static MSG_BEGIN_INIT_GRAPHIC_VIEW = "MSG_BEGIN_INIT_GRAPHIC_VIEW";
  public static MSG_END_INIT_GRAPHIC_VIEW = "MSG_END_INIT_GRAPHIC_VIEW";

  public static MSG_BEGIN_INIT_SVG_DIAGRAM_VIEW = "MSG_BEGIN_INIT_SVG_DIAGRAM_VIEW";
  public static MSG_END_INIT_SVG_DIAGRAM_VIEW = "MSG_END_INIT_SVG_DIAGRAM_VIEW";

  public static MSG_FREEZE_SELECTION = "MSG_FREEZE_SELECTION";
  public static MSG_RIGHTS_LOADED = "MSG_RIGHTS_LOADED";
  public static MSG_PROJECT_CLOSED = "MSG_PROJECT_CLOSED";

  public static MSG_RULE_LIST_CHANGED = "MSG_RULE_LIST_CHANGED";
  public static MSG_CS_RULE_ENGINE_EXECUTION_START = "MSG_CS_RULE_ENGINE_EXECUTION_START";
  public static MSG_CS_RULE_ENGINE_EXECUTION_END = "MSG_CS_RULE_ENGINE_EXECUTION_END";
  public static MSG_CS_RULE_ENGINE_LOG_CHANGED = "MSG_CS_RULE_ENGINE_LOG_CHANGED";
  public static MSG_PY_RULE_ENGINE_EXECUTION_START = "MSG_PY_RULE_ENGINE_EXECUTION_START";
  public static MSG_PY_RULE_ENGINE_EXECUTION_END = "MSG_PY_RULE_ENGINE_EXECUTION_END";
  public static MSG_PY_RULE_ENGINE_LOG_CHANGED = "MSG_PY_RULE_ENGINE_LOG_CHANGED";

  public static MSG_UPLOADING_FILE = "MSG_UPLOADING_FILE";

  public static MSG_START_SAVE_PROJECT_ON_TABLET = "MSG_START_SAVE_PROJECT_ON_TABLET";
  public static MSG_END_SAVE_PROJECT_ON_TABLET = "MSG_END_SAVE_PROJECT_ON_TABLET";

  public static MSG_START_DELETING_PROJECT_FROM_TABLET = "MSG_START_DELETING_PROJECT_FROM_TABLET";
  public static MSG_END_DELETING_PROJECT_FROM_TABLET = "MSG_END_DELETING_PROJECT_FROM_TABLET";

  public static MSG_PROJECT_IS_DIRTY_CHANGE_ON_TABLET = "MSG_PROJECT_IS_DIRTY_CHANGE_ON_TABLET";

  public static MSG_VERIFICATION_CHANGED = "MSG_VERIFICATION_CHANGED";
}
